### PR TITLE
Adapt to `mountSeries` "renaming" the target realm

### PR DESCRIPTION
**Pull request by JulianKniephoff**
Based on #87.

### CODE REVIEW

**Review by LukasKalbertodt — COMMENTED** [review]
When mounting in an existing page, there is no warning that the title will be overwritten. Is that intended?

**Comment by JulianKniephoff** [comment]
I thought I tested that, but I will have another look. :thinking:

**Comment by LukasKalbertodt** [comment]
I would prefer the note being at the bottom. For one, with many realms in the table, the notification might be scrolled out of view. And also, it appearing and disappearing causes the current text field to shift around, which is a jarring UX.

**Comment by LukasKalbertodt** [comment]
:+1:

**Pull request merged**
